### ISSUE TITLE
An error occurred  

### ISSUE THREAD

**Issue by MJFalahi** [pouriya/tir#8]
Hi.
There is a problem with executing " tir "
Given error :

```
Traceback (most recent call last):
  File "/usr/local/bin/tir", line 619, in <module>
    main(data)
  File "/usr/local/bin/tir", line 508, in main
    transformed = HTMLParser(data, transformers).parse()
  File "/usr/local/lib/python3.8/dist-packages/tir-19.10.7-py3.8.egg/tir/tir.py", line 282, in parse
    transform_data[name] = transformer(self.html)
  File "/usr/local/bin/tir", line 97, in find_dates
    solar = find_date(rows, 'shamsi')
  File "/usr/local/bin/tir", line 107, in find_date
    (weekday, (year, month_name, day)) = transform_date(date)
  File "/usr/local/lib/python3.8/dist-packages/tir-19.10.7-py3.8.egg/tir/tir.py", line 61, in transform_date
    date = transform_date_with_string_month(data[1].strip())
  File "/usr/local/lib/python3.8/dist-packages/tir-19.10.7-py3.8.egg/tir/tir.py", line 85, in transform_date_with_string_month
    ,transform_month(date[1])
  File "/usr/local/lib/python3.8/dist-packages/tir-19.10.7-py3.8.egg/tir/tir.py", line 177, in transform_month
    raise ValueError('unknown solar month {!r}'.format(month))
ValueError: unknown solar month 'اَمرداد'

```

**Comment by pouriya** [comment]
Thank you @MJFalahi. As you can see, We are working on it. It'll be fixed today, if possible. At the latest - by tomorrow.

**Comment by pouriya** [comment]
Tir v20.07.26 is out. You can update to master and run `make install` again. Thank you and @tacrazymage very much.
